config/routes.rb
Rails.application.routes.draw do

  resources :meetings
  resources :rooms
  resources :users

  resources :users do
    resources :meetings
  end

  get 'rooms/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  #post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  #get '/activate',   to: 'account_activations#activate'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :user_id, presence: true
  validates :room_id, presence: true
  validates :name, presence: true
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]


  # GET /meetings
  # GET /meetings.json
  def index
  @meetings = Meeting.where(user_id:params[:user_id]).to_ary
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    respond_to do |format|
      if @meeting.save
             format.html { redirect_to @meeting, notice: 'meeting was successfully created.' }
             format.json { render :show, status: :created, location: @meeting }
           else
             format.html { render :new }
             format.json { render json: @meeting.errors, status: :unprocessable_entity }
           end
       end
     end



  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    @meeting.update(meeting_params)
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:user_id, :room_id, :start_time, :end_time)
    end

end

app/helpers/meetings_helper.rb
module MeetingsHelper
  
  def get_user_name(id)
   User.find(id).name
end
def get_room_name(id)
   Room.find(id).name
end

end

app/views/meetings/_form.html.erb
<%= form_with(model: @meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if logged_in? %>
    <div class="form-group">
      <%= form.label :user_id %>
      <%= form.text_field :user_name, value: current_user.name, disabled:'disabled',class:"form-control" %>
      <%= form.hidden_field :user_id, value: current_user.id %>
    </div>

    <div class="form-group">
      <%= form.label :room_id %>
      <%= collection_select(:meeting, :room_id, Room.where(status:"In Use").to_ary, :id, :name, {}, { class: "form-control" }) %>
    </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>


  <div class="actions">
    <%= form.submit "book" %>
  </div>

  <% else %>
        <%= flash.now[:danger] = 'Please log in before make bookings' %>
        <%= link_to "Log in", login_path %>
<% end %>

<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', user_meeting_path(@meeting.user_id, @meeting.id)  %> |
<%= link_to 'Back', user_meetings_path %>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meetings</h1>

<table>
  <thead>
    <tr>
      <th>Room</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= get_room_name(meeting.room_id) %></td>
        <td><%= meeting.start_time %></td>
        <td><%= meeting.end_time %></td>
        <td><%= link_to 'Show', user_meeting_path(meeting.user_id, meeting.id) %></td>
        <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting', new_user_meeting_path(current_user.id) %>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= get_room_name(@meeting.room_id) %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @meeting.end_time %>
</p>



<%= link_to 'Edit', edit_user_meeting_path(@meeting.user_id, @meeting.id) %> |
<%= link_to 'Back', user_meetings_path(@meeting.user_id) %>