config/routes.rb
Rails.application.routes.draw do

  resources :meetings
  resources :rooms
  resources :users

  resources :users do
    resources :meetings
  end

  get 'rooms/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  #post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  #get '/activate',   to: 'account_activations#activate'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :meetings, dependent: :destroy
  validates :name, presence: true

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]



  def index
    @rooms = Room.all
  end

  def show
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      flash[:success] = "New room created!"
      redirect_to @room

    else
      render 'new'
    end
  end

  def destroy
    @room.destroy
    flash[:success] = "Room deleted"
    redirect_to users_url
  end

  private

  def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:name, :location, :status)
    end



end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if logged_in? && is_admin? %>
    <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

    <div class="form-group">
    <%= form.label :location %>
    <%= form.text_field :location,class:"form-control" %>
  </div>

    <div class="form-group">
    <%= form.label :status %>
    <%= form.select(:status, ['In Use', 'Not In Use'] ,{}, {class:"form-control"}) %>
  </div>

    <div class="actions">
    <%= form.submit class:"btn btn-primary form-control" %>
  </div>
  <% else %>
          <%= flash.now[:danger] = "You don't have authority add/modify meeting room." %>
  <% end %>
<% end %>

app/views/rooms/index.html.erb
<% provide(:title, "View All Rooms") %>

<h1>Rooms</h1>

<table class="table">
  <thead  class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.location %></td>
        <td><%= room.status %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to_if(logged_in? && is_admin?, 'Edit', edit_room_path(room)) do
               link_to("","#")
                end %>
        </td>
        <td><%= link_to_if(logged_in? && is_admin?, 'Delete',  room_path(room.id), method: :delete, data: { confirm: 'Are you sure to delete this meeting room?' }) do
         link_to("","#")
                end  %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<% provide(:title, 'Create room') %>
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<%= stylesheet_link_tag "/custom.css" %>



<div class="room">
        <strong>Name:</strong>
        <%= @room.name %>

</div>

<p>
  <strong>Location:</strong>
  <%= @room.location %>
</p>

<p>
  <strong>Status:</strong>
  <%= @room.status %>
</p>


<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>