config/routes.rb
Rails.application.routes.draw do

  resources :meetings
  resources :rooms
  resources :users

  resources :users do
    resources :meetings
  end

  get 'rooms/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  #post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  #get '/activate',   to: 'account_activations#activate'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "/custom.css" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
        <nav>
          <ul class="topnav">
            <li class="items"><%= link_to "Logo", root_path, id: "logo" %></li>
            <li class="items"><%= link_to "Home",   root_path %></li>
            <li class="items"><%= link_to "Help",   help_path %></li>
            <% if logged_in? %>
              <li class="items"><%= link_to "Users", users_path %></li>
              <% if is_admin? %>
                <li class="items"><%= link_to "Manage Rooms", rooms_path %></li>

              <% end %>
              <li class="items"><%= link_to "New Booking", new_user_meeting_path(current_user.id) %></li>
              <li class="items"><%= link_to "View My Bookings", user_meetings_path(current_user.id) %></li>
              <li class="dropdown">
                <a href="javascript:void(0)" class="dropbtn" data-toggle="dropdown">
                  Account </a>
                  <div class="dropdown-content">
                    <%= link_to "Profile", current_user %>
                    <%= link_to "Settings", edit_user_path(current_user) %>
                    <%= link_to "Log out", logout_path, method: :delete %>
                  </div>
            </li>

        <% else %>
          <li class="items"><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
        </nav>

        <% flash.each do |message_type, message| %>
       <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
     <% end %>

    </header>

    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>